language: node_js
node_js:
- '0.12'
sudo: false
before_install: 
  - npm install grunt-cli -g 
  - npm install protractor -g
  - npm install bower -g  
install: npm install
before_script: grunt build --verbose
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
deploy:
  api_key:
    secure: ESB3nOem1WxaITqdj6J1w5XfACo1s6RuwoaCEsyiaqj46tpNHFL6m1SxFkfbbMXO0yvn7czD3yYXl6KZTteQxLvufoZcu+j7aopc7+2fX9sDp5bsDFyom0SY4NM0Lcp+Gg/O0qH63KPCjILwaGktm+nh84T4Z2qUaCQ2mKsUH/aA5IZmHicQuedV548ipYhEeZ0kk1hgZqViEcJPX32mRHeNHy+QAZRche0L378SPdZp2mRZzswpNg6jWjyzTONln51Dsgvv1ptijbyVv69K3wReKBJkKERKE5s2Zz/H1zu0Ty4oe23tsi9ao9mQhWjyaPFMOd+4LTNLFiI6NqNQNXyTlf9NTdq4389lhXfAlH7LBdrcVbyENGu7GfLG5laDLgH+DynNdYMGdwhKJ2Uadj4Wj+8kG6Ev73MUT9of4y7vHNUh1dZ+GS+91cNt3vqAjo14EOYBG5fNCCed77wPzff0K9iQJmFvcCztrxT0C5VT2oAh5NdOKfRYBgRHkaSHpk6nLmpXoKlVbGH35HNUSVpSfEt6ZI4MP9AX9E4xH7chlAf0KfjEx9/uGui2UIg7DVndgMtNH/kfSgIDA1AGU4N/gR/pUYA5lXbo0sR9kp7S7e5tSJ92IWbAFF4hEzhtFuW/Lgr2qfV/pcdoff4temB1HBXz75pb0kM0ARP4Zp8=
