consultorio_online_app-elasticsearch:
  container_name: consultorio_online_app-elasticsearch
  image: elasticsearch:1.7.3
  # volumes:
  #   - ~/volumes/jhipster/consultorio_online_app/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
consultorio_online_app-postgresql:
  container_name: consultorio_online_app-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/consultorio_online_app/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=consultorio_online_app
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
