consultorio_online_ui-elasticsearch:
  container_name: consultorio_online_ui-elasticsearch
  image: elasticsearch:1.7.3
  # volumes:
  #   - ~/volumes/jhipster/consultorio_online_ui/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
consultorio_online_ui-mysql:
  container_name: consultorio_online_ui-mysql
  image: mysql:5.7.9
  # volumes:
  #   - ~/volumes/jhipster/consultorio_online_ui/mysql/:/var/lib/mysql/
  environment:
    - MYSQL_USER=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=consultorio_online_ui
  ports:
    - "3306:3306"
  command: mysqld --lower_case_table_names=1
